[package]
name = "remo-graph"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.98"
base64 = "0.22.1"
clap = { version = "4.5.38", features = ["derive"] }
futures = { version = "0.3.31", default-features = false, features = ["std"] }
log = "0.4.27"
reqwest = { version = "0.12.15", default-features = false, features = ["charset", "http2", "json", "macos-system-configuration", "rustls-tls-webpki-roots"] }
serde = { version = "1.0.219", features = ["derive"] }
time = { version = "0.3.41", features = ["serde-well-known"] }
tokio = { version = "1.45.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[profile.release]
codegen-units = 1
lto = true
strip = true
